### ISSUE TITLE
Exclude Unnecessary Files

### ISSUE THREAD

**Issue by evshiron** [evshiron/nwjs-builder#1]

**Comment by conceptualspace** [comment]
👍

**Comment by evshiron** [comment]
@conceptualspace Thanks for the thumb up.
In fact the files that need to be removed are varying across nw.js versions. It's a refining step without which everything will still work. That's why the idea is on hold at the moment.
If you want this to be added as a feature, please provide some examples so that I can know why and how to implement it. Thanks.

**Comment by conceptualspace** [comment]
yes --

originally i was surprised at how many files were included in the nwjs-builder output (coming to nw 0.14 from 0.11), but the output matches a stock nwjs download so it's not an issue with the builder but with nwjs itself. would still be a nice feature though, so i'll investigate more as time permits
