### ISSUE TITLE
Extract & use already downloaded nw.js

### ISSUE THREAD

**Issue by arhangelsoft** [evshiron/nwjs-builder#13]
Greetings, in the some situations I've download the nw.js using some app due low connection speed.
Can you include feature "Extact and cache already downloaded nw.js builds from path"?

e.g. download what I needmanually, put them to some "/cache/downloaded/" and run "nwd cache invalidate"

**Comment by evshiron** [comment]
The caches are stored in `~/.nwjs-download/caches/`. You may want to download a nw.js binary, prepend "binary-" to its filename and copy it to the caches directory. This should do the trick.
Reference: https://github.com/evshiron/nwjs-download/blob/master/lib/util.js#L108
Feel free to ask if you have further questions :)

**Comment by arhangelsoft** [comment]
Maybe that trick should be put on readme.md or wiki )

**Comment by evshiron** [comment]
Good idea, added to the plan. Thanks :)
