### ISSUE TITLE
Travis CI Build Failed

### ISSUE THREAD

**Issue by evshiron** [evshiron/nwjs-builder#18]
I have added a `test-module.js`, which uses in progress features like destructuring (`--harmony-destructuring` will fix, but it also prevent node.js 6.x from launching), and the Windows build process on Linux requires a usable `wine`. That's why the Travis CI build failed.
Any ideas about how to fix this?

**Comment by orther** [comment]
Almost all the npm packages I see published to npm get transpired before being published so it's es5 code ready for use in projects without es6 support. Did you decide to not do that or is it just an oversight?

An example would be the `prepublish` script in this post https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/

**Comment by evshiron** [comment]
I admit it is an oversight. Personally I don't like transpilers because it's not direct and using plain ECMAScript 6 works well in my simple projects. However things are different when it's published and to be used in various environments.
I will learn about it and consider how to do it perfectly. Thanks for the helpful link :)

**Comment by evshiron** [comment]
`nwjs-builder` 1.8.0 uses `babel` now and the failing build has been fixed.
