### ISSUE TITLE
Cannot build without side-by-side

### ISSUE THREAD

**Issue by darshanshankar** [evshiron/nwjs-builder#19]
Win 10, Node 4.4, nwjs 0.14.5, nwjs-builder 1.6.0

Can't open my app if I use `--side-by-side` to build it. Getting a checksum error when using 7zip to unzip the .exe binary. Any idea why that could be?

**Comment by evshiron** [comment]
Thanks for the report. This is because `Util.CombineApplication` doesn't work as expected on Windows (and results in a `copy /b a.exe b.exe`). I am looking into it.

**Comment by evshiron** [comment]
Uh-huh, it seems like an issue with `rcedit.exe` now.

**Comment by evshiron** [comment]
Fixed now. By simply editing executable before combining application. Please upgrade to `nwjs-builder` 1.8.1.
