### ISSUE TITLE
Cannot find module 'nwjs-builder'

### ISSUE THREAD

**Issue by mato75** [evshiron/nwjs-builder#22]
Tried require('nwjs-builder'); and require('evshiron/nwjs-builder');

**Comment by evshiron** [comment]
Please make sure the installation is successful. BTW the proper way to require is `require('nwjs-builder')`.
Feel free to ask if you have further questions.

**Comment by mato75** [comment]
Installation was successful, but I see in Travis, that master was successfully tested 10min ago. Will install it again.

**Comment by evshiron** [comment]
That build failed because `mocha` was broken when it bumped its version to 2.5.0, and it's fixed now in 2.5.1.

**Comment by mato75** [comment]
Ok, then I don't know what could cause this issue. I see nwjs-builder in node_modules, but cannot access is through require. 

Is this still correct way to install it:
npm install evshiron/nwjs-builder -g

**Comment by evshiron** [comment]
No. Please read https://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation/.
In general, a global installation means the module provides an executable. If you want to use it in your project, use local installation instead.

**Comment by mato75** [comment]
I installed it also locally.

**Comment by evshiron** [comment]
Try removing `node_modules/node-flow/`, `node_modules/nwjs-download/` and `node_modules/nwjs-builder/` and `npm install nwjs-builder` again.
If the requiring still fails, please provide some console output along with the reply, which will help me discover where the problem is.

**Comment by evshiron** [comment]
Oh wait. Install it by `npm install nwjs-builder`. Not `npm install evshiron/nwjs-builder`, which will fetch stuff from GitHub directly.
Sorry about that. It's time to update the README.

**Comment by mato75** [comment]
That was it, thx.
