### ISSUE TITLE
output name not working?

### ISSUE THREAD

**Issue by conceptualspace** [evshiron/nwjs-builder#25]
seeing the error,

`unknown option '--output-name'`

v 1.10.5

**Comment by nicklaw5** [comment]
@conceptualspace as mentioned [here](https://github.com/evshiron/nwjs-builder/issues/3#issuecomment-222495386), the `--output-name` uses a string-template.

Running the below worked for me:
`nwb nwbuild -v 0.15.0-sdk -p win64 --output-name "{name}-v{version}-{target}" ./build/`

And resulted in `stryve-v0.3.0-alpha-win-x64` as the output folder name.

Note that `{name}` and `{version}` pull from your `package.json` file.

**Comment by conceptualspace** [comment]
hmm, still no dice for me...

osx 10.11.5
npm 3.8.3
nw 0.14.4
nwjs-builder 10.1.5

**Comment by conceptualspace** [comment]
my bad, had conflicting versions of nwjs-builder installed

**Comment by evshiron** [comment]
@nicklaw5 Greetings. The templating provides only `name`, `version`, `platform`, `arch` and `target`, not from `package.json` (see also commits). If there is a need I can add it in the next version.
