### ISSUE TITLE
Build is showing default NW.js window

### ISSUE THREAD

**Issue by MrHalfman** [evshiron/nwjs-builder#27]
Hi,

When I try to build from Linux to Windows I get the default NW.js window (Tried 32 and 64 bits versions) :
![capture](https://cloud.githubusercontent.com/assets/3469538/15704315/68476712-27ea-11e6-91eb-68a0a79616d4.PNG)

My package.json seems correct as it runs well if I launch the app manually using the nw.js binary.

Thanks for you help :smile:.

**Comment by evshiron** [comment]
Could you try `nwb nwbuild -r ./build/` or building with `--side-by-side` enabled and see if that works? I have run my `win32` test build just now and it worked as expected.

**Comment by MrHalfman** [comment]
Thanks for the fast answer. Running the app using -r works, 

It also works with --side-by-side but it leaves my code in the output directory and anybody can read it easily :/.

I don't see why the "normal" build isn't working

**Comment by evshiron** [comment]
So it's an issue with the `Util.CombineApplication` again? It should be fixed for a long time.
Could you tell me what version of node.js you are using?
BTW if you have time, try `git clone https://github.com/evshiron/nwjs-builder && cd nwjs-builder && npm install && npm test`. This will do the tests and build a `win32` "normal" build in `./temp/build/nwb-test-v0.0.1-win-ia32/`, which simply exits after launching (no default window). If tests timeout, feel free to increase timeout in `src/test/test-*.js` and `npm test` again.

**Comment by MrHalfman** [comment]
I'm going to try the tests, here is my node versions :
`{ npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.1.1',
  openssl: '1.0.2e',
  uv: '1.7.5',
  v8: '4.6.85.31',
  zlib: '1.2.8' }`

**Comment by MrHalfman** [comment]
Tests are okay : `7 passing (3m)`. I don't see why it works with side-by-side only :(. 

Should I update my Node.JS?

**Comment by evshiron** [comment]
@MrHalfman Did you try launching `./temp/build/nwb-test-v0.0.1-win-ia32/NWBTest.exe` on your Windows and it should simply exit? It works as expected in my case though.

**Comment by MrHalfman** [comment]
I found the problem, it's Windows' fault (astonishing....), Windows has a limit of 256 chars for paths and I had a node_module which had dependencies with dependencies with dependencies etc.

This module was not essential so, I removed it easily and my app works now :tada:!

**Comment by evshiron** [comment]
@MrHalfman Glad to know that!

**Comment by evshiron** [comment]
BTW shouldn't npm 3 install dependencies in a flat structure?

**Comment by MrHalfman** [comment]
Maybe I installed the dependencies with an old version.
