### ISSUE TITLE
Can`t build for v0.12.3

### ISSUE THREAD

**Issue by scorpioRED** [evshiron/nwjs-builder#28]
In folder with my project I try to do :

MacBook-Air-Vitaliy:change_ip scorpio$ nwb nwbuild -v 0.12.3-sdk -p win32,osx64 ./build/
ERROR_VERSION_NOT_FOUND
version: 0.12.3-sdk
versions: [ 'v0.15.1',
  'v0.14.6',
  'v0.15.0',
  'v0.15.0-rc2',
  'v0.14.5',
  'v0.14.4',
  'v0.15.0-rc1',
  'v0.15.0-beta2',
  'v0.14.3',
  'v0.15.0-beta1',
  'v0.14.2',
  'v0.14.1',
  'v0.14.0',
  'v0.13.4',
  'v0.14.0-rc3',
  'v0.13.3',
  'v0.14.0-rc2',
  'v0.14.0-rc1',
  'v0.13.2',
  'v0.13.1',
  'v0.13.0',
  'v0.13.0-rc4',
  'v0.13.0-rc3',
  'v0.13.0-rc2',
  'v0.13.0-rc1',
  'v0.13.0-beta7',
  'v0.13.0-beta6',
  'v0.13.0-beta5',
  'v0.13.0-beta4',
  'v0.13.0-beta3',
  'v0.13.0-beta2',
  'v0.13.0-beta1',
  'v0.12.3' ]
MacBook-Air-Vitaliy:change_ip scorpio$ 

or

MacBook-Air-Vitaliy:change_ip scorpio$ nwb nwbuild -v 0.13.1-sdk -p win32,osx64
{ version: 'v0.13.1',
  flavor: 'sdk',
  targets: [ [ 'win', 'x86' ], [ 'osx', 'x64' ] ],
  path: '.' }
0: Read package.json
1: Prepare build directory at changeaddress-win-ia32
2: Copy binary from /Users/scorpio/.nwjs-builder/caches/binary-nwjs-sdk-v0.13.1-win-ia32
3: Edit Windows executable
{ [Error: spawn wine ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs: 
   [ '/usr/local/lib/node_modules/nwjs-builder/node_modules/rcedit/bin/rcedit.exe',
     'changeaddress-win-ia32/nw.exe',
     '--set-version-string',
     'ProductName',
     'tst',
     '--set-version-string',
     'FileDescription',
     'none',
     '--set-product-version',
     '0.0.1' ] }
MacBook-Air-Vitaliy:change_ip scorpio$ 

Where is mistake?

**Comment by evshiron** [comment]
@scorpioRED Greetings. nw.js 0.12.3 doesn't have a `sdk` flavor, only `normal` and `macappstore` (according to `nwb list`, which prints from `http://nwjs.io/versions.json`). And for Windows builds, we need `wine` to launch `rcedit.exe` for editing `name`, `version`, `description`, `icon` of the executable.
I think it's better to skip the step and print a warning when `wine` is unavailable though.

**Comment by evshiron** [comment]
Everything should work now. If you have further issues, feel free to reopen or make a new one.
