### ISSUE TITLE
[Feature Request] Zipping Platform Build Option

### ISSUE THREAD

**Issue by nicklaw5** [evshiron/nwjs-builder#29]
Would be great if the build process included an option for outputting a zipped version of the build, as opposed to a large build folder.

I have implemented this in my [build.js](https://github.com/nicklaw5/stryve/blob/master/build.js#L67-L114) script, but seems like it should be something included in this package as an option.

Somthing like this:
```bash
$ nwb nwbuild -h

  Usage: nwbuild [options] [PATH_OR_ARGS...]

  Options:
    -z,--zip                                  Outputs a zipped version of each platform build
```

**Comment by evshiron** [comment]
@nicklaw5 Greetings. I have added an `--output-format` option in `nwjs-builder` 0.11.0. `--output-format ZIP` should produce `.zip` instead of a directory.

**Comment by nicklaw5** [comment]
Thanks. Works great!
