### ISSUE TITLE
More nwbuild Options?

### ISSUE THREAD

**Issue by evshiron** [evshiron/nwjs-builder#3]

**Comment by evshiron** [comment]
`--with-ffmpeg` is added now. What about `--no-appnw`, which doesn't combine `app.nw` to the executable?

**Comment by evshiron** [comment]
`--side-by-side` is added too.

**Comment by evshiron** [comment]
Propose: `--production`, which doesn't copy the `node_modules`, but execute `npm install --production` when copying is done, which will strip devDependencies out and reduce file size.

**Comment by evshiron** [comment]
`--production` is added in 039e866.

**Comment by evshiron** [comment]
Propose: `--win-ico` and `--osx-icns`.

**Comment by nicklaw5** [comment]
-o, --buildDir <buildPath> The build folder [default: "./build"]

**Comment by evshiron** [comment]
@nicklaw5 Thanks for the suggestion, added in 820718d. README and published version is also updated.

**Comment by conceptualspace** [comment]
+1 for icons

**Comment by evshiron** [comment]
@conceptualspace `--win-ico` and `--mac-icns` are added long ago. Feel free to try them out and feedback is appreciated.

**Comment by conceptualspace** [comment]
will do! and thanks for your work on this

**Comment by mato75** [comment]
Can you please update README with all the options that are available.

**Comment by evshiron** [comment]
I think all the options are listed in the "Usage" section. If you want a reference, please see `test/test-module.js`.

**Comment by mato75** [comment]
Options that would be awesome to have:

````
argv: [], // custom arguments passed to nwjs
port: 1245 // custom port on which nwjs is running
````

**Comment by evshiron** [comment]
What's the `port` means? Is it for `--remote-debugging`? It's a good propose though. I will consider adding it in the next days.

**Comment by mato75** [comment]
Yes for remote debugging. Sorry for port, but argv would be nice to have. I am passing custom arguments, like web socket port, server address, ...

I am using nwjs for testing.

**Comment by evshiron** [comment]
I will see how underlying commander.js supports this.

**Comment by evshiron** [comment]
@mato75 Custom arguments should be usable in `nwjs-builder` 1.10.0. There are examples in README and `test/test-nwbuild.js`. Feel free to try it out.

**Comment by mato75** [comment]
How do you set them when used inside *.js (I dont see an extra option, that will allow me to add custom arguments)?

**Comment by evshiron** [comment]
@mato75 This should work:
```javascript
const NWB = require('nwjs-builder');

NWB.commands.nwbuild(['--remote-debugging-port=9222', './build/', '-a', 'bbb'], {
    run: true
}, (err, code) => {});
```

**Comment by nicklaw5** [comment]
Would be great if there was an option to include the version number in the build folder name.

For example, `stryve-v0.3.0-win-x64` rather than just `stryve-win-x64`

**Comment by evshiron** [comment]
@nicklaw5 `--output-name` is added in `nwjs-builder` 1.10.5. The feature is powered by `string-template` and in your situation `--output-name "{name}-v{version}-{target}"` should do the trick.

**Comment by evshiron** [comment]
I am closing this issue now as it's too long. If there are any proposes, feel free to open a new issue.
