### ISSUE TITLE
Blank ".done" directory created during output

### ISSUE THREAD

**Issue by BoatsAreRockable** [evshiron/nwjs-builder#31]
A very small bug I've noticed is that a blank directory titled `.done` is created in the output directories for all platforms.

**Comment by evshiron** [comment]
Thanks for the report. The `.done` is created to indicate a decompressing process is succeeded. And yes it should be fixed, please wait until I have some time to have it settled later in this day.

**Comment by evshiron** [comment]
In `nwjs-builder` 1.11.2, the `.done` directory will not be included in builds.

**Comment by BoatsAreRockable** [comment]
This issue does not to appear to have been resolved in 1.11.15.

**Comment by evshiron** [comment]
@BoatsAreRockable But it's tested in `test-module.js` and if there is a `.done`, the test will fail. Feel free to reopen this issue and it is appreciated if more information is provided.
