### ISSUE TITLE
Possibility to run with FFmpeg

### ISSUE THREAD

**Issue by vzamanillo** [evshiron/nwjs-builder#34]
It would be interesting the possibility to run with `withFFmpeg`.

**Comment by evshiron** [comment]
In the past, `nwjs-builder` runs nw.js directly from the cache directory, but this will no longer work if `withFFmpeg` is supported. I am considering launching it from a temporary directory where copying and overwriting is allowed.

**Comment by evshiron** [comment]
So a temporary working directory is used. The feature is published in `nwjs-builder` 1.12.0.

**Comment by vzamanillo** [comment]
Thank you, great work!

**Comment by evshiron** [comment]
@vzamanillo Feel free to test it and see if it works :)

**Comment by vzamanillo** [comment]
It works like a charm.

**Comment by evshiron** [comment]
Cool. Glad to know 👍
