### ISSUE TITLE
Windows icon does not scale correctly

### ISSUE THREAD

**Issue by BoatsAreRockable** [evshiron/nwjs-builder#38]
When my app is exported using the `win-ico` option the resulting executable has an icon that does not scale. This means that it appears pixelated when set as a desktop icon, pinned to the Windows 10 start screen or simply zoomed into in the File Explorer.

Using Resource Hacker I can see that an icon group with different sizes has been generated; it just does not seem to be using them correctly.

**Comment by evshiron** [comment]
Thanks for the report.
I know there are some limitations with the integrated `rcedit.exe`, but I only have a Windows 7 VM and indicated from the "nwb-test" (the testing application built in the testing procedure) it looks acceptable (high resolution in File Explorer and Taskbar).
Would you mind helping me run the tests on your Windows 10 machine and see if the "nwb-test" application (located in `/temp/` directory) looks good?
Also recommended command line tools to solve this issue are appreciated too.
See CONTRIBUTING for a brief procedure to run the tests.

**Comment by BoatsAreRockable** [comment]
I've just run `npm test` and it's failing with: `Uncaught Error: ERROR_DONE_FILE_EXISTS` (I assume this is related to #31).

The test application located at `temp\build\nwb-test-win-ia32` unfortunately has the low res icon. If file explorer is set to the large icon view this becomes very clear:

<img width="600" alt="nwjs-builder icon issue" src="https://cloud.githubusercontent.com/assets/8095888/16376070/76c161b4-3c56-11e6-880c-9a26fe9aa4b8.PNG">

I've noticed the same icon issue has actually been reported as [atom/node-rcedit/issues/4](https://github.com/atom/node-rcedit/issues/4).

Some alternative tools I've found:
* https://github.com/felicienfrancois/node-resourcehacker
* https://github.com/felicienfrancois/node-winresourcer

**Comment by evshiron** [comment]
@BoatsAreRockable Cool and thanks a lot!
In #31 I forget the separator difference of Windows, and the alternatives look promising. `node-winresourcer` should be used in `nw-builder` and I think it doesn't support editing stuff other than icons, so I am going to try `node-resourcehacker`.
BTW, did you manage to use Resource Hacker to get around this?

**Comment by BoatsAreRockable** [comment]
I've just tested node-resourcehacker in my build process and it does indeed fix this :)

**Comment by evshiron** [comment]
Excellent.
I have read https://github.com/nwjs/nw-builder/issues/44 and there are wrapper modules like `winresourcer` and `resourcehacker`. Because `winresourcer` requires .NET Framework 2.0, which will be much complicated on Linux/Mac OS X, I decide to use `resourcehacker`.
But the `resourcehacker` wrapper seems to split the arguments by space, which I think will lead to problems when there are spaces in the path. I am thinking about wrapping it myself, but it will take some time.

**Comment by evshiron** [comment]
This issue should be fixed in `nwjs-builder` 1.12.2, as well as #31, but I have only tested it on Linux (Travis CI) and Mac OS X. Feel free to try it out :)

**Comment by evshiron** [comment]
It's a pity I can't include a copy of Resource Hacker because of it's license.
I have to download it in the post-install step and it's extremely slow in my case. Maybe I can make it an optional dependency so that we download it only when we need it.

**Comment by BoatsAreRockable** [comment]
This issue has not been resolved in 1.12.2 - now the icon is not changed at all from the default.

I've looked at `src/lib/build/win32` and it appears you are using [node-resourcehacker](/felicienfrancois/node-resourcehacker) but with a method from [node-winresourcer](https://github.com/felicienfrancois/node-winresourcer)!

**Comment by evshiron** [comment]
Hmm, not an expected behavior. Because I thought `resourcehacker` might have some problems with spaces, I made a wrapper and published it as `node-resourcehacker` (but I suspect it use commas as separator), but there should not be a problem with the function call.
I will test again on a Windows 7 machine myself.

**Comment by evshiron** [comment]
BTW there is a `ResourceHacker.log` in `node_modules/node-resourcehacker/` and when I run the tests on Windows it says 'Error: "assets/nwb-test.ico" does not exist', which is quite strange.

**Comment by evshiron** [comment]
@BoatsAreRockable As `node-resourcehacker` 1.0.1 published, the tests should generate correct icons on Windows. Please help test it and see if everything works as expected, thanks.

**Comment by BoatsAreRockable** [comment]
@evshiron the tests fail with:
`Uncaught TypeError: Cannot read property 'normalize' of undefined`

However, I think I've found the issue which just be quite a simple fix. Please see [my comment](https://github.com/evshiron/node-resourcehacker/commit/36795958ec7a083c831d6cb30d488b1b0b9d11ea) on your `node-resourcehacker` commit.

**Comment by evshiron** [comment]
@BoatsAreRockable Ouch... Haven't been writing ECMAScript 5 for a long time and forget the naming stuff. Should be fixed in `node-resourcehacker` 1.0.3 now.

**Comment by BoatsAreRockable** [comment]
1.0.3 fixes this :+1: 

Thank you for fixing this so quickly!
