### ISSUE TITLE
Linux builds are incredibly large

### ISSUE THREAD

**Issue by rstacruz** [evshiron/nwjs-builder#46]
My Linux build is something like 600mb+, ouch. Any way to optimize this?

**Comment by evshiron** [comment]
@rstacruz ahuh, what options are you using? Did you try `--production` or `--side-by-side` option? Do you know who is occupying most of the space?

**Comment by rstacruz** [comment]
ahh, i'll have to try those! what's side-by-side?

**Comment by evshiron** [comment]
`--side-by-side` means not to combine the application package to the executable (that `copy /b nw+app.nw app` step).
From #47, I assume you are running `nwjs-builder` directly in your project root, which will no doubt include every file in that directory.
You might want to read [Development](https://github.com/evshiron/nwjs-builder#development) section which I have explained why there isn't an excluding option.
Most of the time you might be using some compilers/transpilers to transform the source code and have a lot of dependencies only used in development stage, along with tests and scripts. They are not going to be packaged when doing a release.
So my suggestion is filling release files to a directory and using `nwjs-builder` to pack that directory. So there is no excluding needed :)

**Comment by rstacruz** [comment]
Ahhh, right. My app uses no transpilation (node.js 6 supports most of es6
anyway), so I was pretty concerned about that!

**Comment by rstacruz** [comment]
Any hints on how to do that? Will I need 2 package.json's?

**Comment by evshiron** [comment]
node.js 6.x is cool :)
`nwjs-builder` used to require extra flags like `--harmony-destructuring` to work on node.js 4.x/5.x, and doesn't support legacy versions. But after publishing there were complaints for it and I started to use `babel` :)

**Comment by evshiron** [comment]
@rstacruz No. You can write a `build.sh` (or any other task runners) which copies every file you want to include (like `package.json`) to a separate directory and call `nwjs-builder` to make a bundle of it.
