### ISSUE TITLE
native modules stopped working after build

### ISSUE THREAD

**Issue by Zuzon** [evshiron/nwjs-builder#48]
Native modules not working after build, 
I use win8.1 vs2013.
works only with --side-by-side and only on my machine, if i copy to another machine, it stops working

**Comment by evshiron** [comment]
@Zuzon I am sorry I didn't have any experience with native modules.
Could you try manually packaging your application by following the steps in [Package and Distribute](http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/) and see if it works both locally and on another machine?
