### ISSUE TITLE
Integrate nwjs-ffmpeg-prebuilt

### ISSUE THREAD

**Issue by evshiron** [evshiron/nwjs-builder#5]
https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases

**Comment by evshiron** [comment]
Done in 47ab8b9. Building is successful but it remains untested as I don't have a project which requires this feature.

**Comment by gautaz** [comment]
Hello,

I've just tested with a project targeted on linux64 and it seems that there is one issue regarding the location where the prebuilt binary is installed.

The prebuilt `libffmpeg.so` is installed at the root of the package and does not replace the original library which is located under `lib`. The app was not able to decode H264 videos until I relocated the prebuilt library in `lib`.

Hope this helps.

**Comment by evshiron** [comment]
@gautaz You are right. Thanks for the report. It should be fixed in a minute :)

**Comment by evshiron** [comment]
Fixed in `nwjs-builder` 1.10.9.

**Comment by gautaz** [comment]
Woah ! That was a fast delivery !
I confirm everything seems now OK, thanks ! :-)
