### ISSUE TITLE
App will not start on OSX Yosemite

### ISSUE THREAD

**Issue by MichalMisiaszek** [evshiron/nwjs-builder#50]
You can’t open the application “STL GUI.app” because it is not supported on this type of Mac.

**Comment by evshiron** [comment]
May I know what nw.js version and architecture you are using? And are they different from your Mac?

**Comment by MichalMisiaszek** [comment]
Hi,
nwsd --version
nwjs 50.0.2661.102

The architecture I set was osx64 and I am on Yosemite, should work fine. In the end I crated app putting directory in app.nw inside as recommended. So this cannot work on OSX (Darwin) ?

Regards

**Comment by evshiron** [comment]
Hmm, strange.
Could you upload a mini sample which is able to reproduce this situation, as well as the versions of node.js, npm and nw.js (I believe the "50.0.2661.102" you said before is the version of the built-in Chromium, not nw.js itself)?

**Comment by MichalMisiaszek** [comment]
I am using nwsd.io web toolkit which comes with all other tools. At the moment version 0.16, 0.16-sdk
I will try to make app to check it over the weekend, for the moment I created package manually and it works.

**Comment by evshiron** [comment]
~~I didn't hear of nwsd.io before, nor Google gives me any results.~~

**Comment by MichalMisiaszek** [comment]
Sorry, I meant nwjs.io.

**Comment by evshiron** [comment]
@MichalMisiaszek Hey friend. I have run the tests for nw.js 0.16.0 and it works well. Do you have a sample or steps on how to reproduce it?

**Comment by MichalMisiaszek** [comment]
Hello,
I tested again with 0.16.0.and I confirm it works on OSX creating correct distribution for osx64, win32 and linux64 (the one I tested). I am still testing --production flag, and I don't fully understand --side-by-side option.
Thanks !

**Comment by evshiron** [comment]
@MichalMisiaszek Thanks for your response!
Q: `--side-by-side`?
A: See [Package and Distribute#package-your-app](http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#package-your-app).
`nwjs-builder` will use "Option 2" by default, and use "Option 1" when `--side-by-side` is provided.

Q: `--production`?
A: See [package.json#devDependencies](https://docs.npmjs.com/files/package.json#devdependencies).
As you know, there might be dependencies which are only required in development (e.g. `webpack`). With `--production`, `nwjs-builder` will not copy original `node_modules` and install `dependencies` according to `package.json`, without `devDependencies`.

**Comment by MichalMisiaszek** [comment]
Thanks, I think there is small issue when building for linux but I will check it. Seems like not all dependencies are included in distribution package.

**Comment by evshiron** [comment]
@MichalMisiaszek Could you post the logs?

**Comment by MichalMisiaszek** [comment]
Where I can find them ? The log printed on screen during execution ? 
I installed script on Windows and build package and it worked with exception that directory specified in package.jason "files": was not included. On OSX everything from app directory is included in Resources.

**Comment by evshiron** [comment]
@MichalMisiaszek Yes. And yes, at the moment `nwjs-builder` doesn't respect the `files` field in `package.json`, instead it packs the contents of the given directory.

**Comment by MichalMisiaszek** [comment]
On OS X it copies full content of directory. For Windows it copies only essencial files.

**Comment by evshiron** [comment]
I don't think there is such strategy. If you consider this an issue, feel free to open a new issue and provide enough information (including a sample) so that things can be quickly fixed.
