### ISSUE TITLE
Generated exe starts slowly on Windows

### ISSUE THREAD

**Issue by phiferd** [evshiron/nwjs-builder#53]
When I package my app (without the "side-by-side" option), startup of the generated app can take one to two minutes (only tested on Windows 10).  This happens every time, not just on the first launch.

When I package it with side-by-side, the app launches instantly.  Here's the command I'm using:

`nwb nwbuild --with-ffmpeg -p win64 --output-name myapp -o build --executable-name myapp --win-ico app.ico`

**Comment by evshiron** [comment]
Greetings.
May I know what's the size of the generated executable? nw.js will unzip `.nw` to a temporary directory before really launching it, if there are many files (for example `node_modules`), it might take long before seeing a window.

**Comment by phiferd** [comment]
95MB.  I am only at the beginning of productionization, so I'm sure there are some things I can clean up.  However, is there any reason the extract files have to be extracted each time the app launches?  Can they just be extracted once and then stored in appdata?

**Comment by evshiron** [comment]
@phiferd Have a look at https://github.com/nwjs/nw-builder/issues/195.
In `nwjs-builder`, `--side-by-side` is used to disable the packaging; and `--production` will not copy `node_modules` and will install dependencies by `npm install --production`, which should remove dependencies for development, for production purpose. Hope these tips help.
And at the end, `nwjs-builder` is designed to work with a directory that is well-prepared to be packaged, so you might need to copy everything needed to a directory before calling `nwjs-builder`. A task runner or Shell script should do the job well.

**Comment by phiferd** [comment]
Ok.  Fair enough.  But even after all that, a large project will not ever launch smoothly if it requires unzipping a lot of files.  This isn't a couple seconds, it's about a minute or more.  Seems like unzipping the dependencies each time is unnecessary, no?

**Comment by evshiron** [comment]
Yes, it is unnecessary. At the very beginning NW.js decided to do so, I am afraid it's not a matter with `nwjs-builder` itself. Electron is inspired by NW.js, but it invented an `.asar` archive format and added access support directly onto the runtimes, so that it doesn't have this kind of issues.
Perhaps the only way to avoid it is not to zip it at all (I mean `--side-by-side`).

**Comment by phiferd** [comment]
I see. Makes sense. Thanks
