### ISSUE TITLE
[Feature request] Add a CLI flag to close itself when nw.js starts. 

### ISSUE THREAD

**Issue by jhm-ciberman** [evshiron/nwjs-builder#58]
The actual behavior when you `--run` a nw.js app is that nwjs-builder finishes only when the nw.js instance finish. 
This makes imposible to integrate nwjs-builder into a build pipeline (like gulp or atom "build" plugin) because the building with `--run` never ends.

Example scenario:
 - Edit some files. And want to test them. PRESS F9 in Atom to launch the build.
 - Atom executes `nwb nwbuild -v v0.19.4-sdk --run .` (via Gulp)
 - nwb launch the nw.js and waits until nw.js window is closed.
 - When the last window is closed nwb closes itself and fire the callback() funcion.
 - Atom reports that the build finished. (In fact, the build finished before, but atom keeps waiting until all the build comands finish)

Expected behavior:
 - Edit some files. And want to test them. PRESS F9 in Atom to launch the build.
 - Atom executes `nwb nwbuild -v v0.19.4-sdk --run-and-close .` (Note the invented `--run-and-close` flag)
 - nwb launch the nw.js AND INMEDIATELY closes itself.
 - Atom reports that the build finished (Now it is true!)
 - The nw.js window opens and you can test it your app. 

If you need help implementing it please tell me, but I am unfamiliar with some of the dependencies you used.

**Comment by evshiron** [comment]
Greetings!

I have added an `--detached` option in version 1.14.0 and it should work like: `nwb nwbuild -v v0.19.4-sdk --run --detached .`

However I used a workaround at [/src/lib/commands.js#L267](https://github.com/evshiron/nwjs-builder/blob/master/src/lib/commands.js#L267), so the `nwjs-builder` will exit with 3 seconds delay.

If there are further issues or if you have an idea about that workaround, let me know.
